# Generated by Django 5.2.6 on 2025-12-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_sweet_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
