# Generated by Django 5.2.6 on 2026-01-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0005_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('CARD', 'Debit / Credit Card')], default='COD', max_length=20),
        ),
    ]
